# <font color='green'> <b>Importing Libraries </b><font color='black'>

In [2]:
import numpy as np
import pandas as pd
# import warnings
# warnings.filterwarnings('ignore') 
#bana warningleri gösterme demek. Notebookun en başında yazabilirsin istersen.

C:\Users\iremtokuroglu\AppData\Local\Temp\ipykernel_13600\1700484108.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [ ]:
dir (pd)

In [ ]:
help(pd.Series)

In [ ]:
?pd.Series

# <font color='green'> <b>Pandas Series </b><font color='black'>

## <font color='blue'> <b>Creating a Pandas Series</b><font color='black'>

Pandas serisi tek boyutlu bir veri yapısıdır. 

Nesneler, objects, floats, strings ve integers dahil olmak üzere birçok türde veri tutabilir. 

pandas.Series() öğesini çağırarak bir seri oluşturabilirsiniz. 

Bir liste, numpy array ve dictionary bir pandas serisine dönüştürülebilir. 

Axis labels (eksen etiketleri) toplu olarak index olarak adlandırılır. 

Unutmayalım ki pandas serilerinin numpy  array lerinden farkı, değerleri indexleriyle beraber tutar.

[SOURCE01](https://pandas.pydata.org/docs/reference/api/pandas.Series.html), 
[SOURCE02](https://www.datasciencemadesimple.com/create-series-in-python-pandas/), 
[SOURCE03](https://www.geeksforgeeks.org/creating-a-pandas-series/),
[SOURCE04](https://towardsdatascience.com/pandas-series-a-lightweight-intro-b7963a0d62a2), 
[SOURCE05](https://www.educba.com/pandas-series/), 
[SOURCE06](http://www.rebellionrider.com/python-pandas-series-in-detail-part-1/), 
[SOURCE07](https://www.javatpoint.com/python-pandas-series), 
[SOURCE08](https://towardsdatascience.com/20-examples-to-master-pandas-series-bc4c68200324) &
[SOURCE09](https://pythonbasics.org/pandas-series/)

### <font color='blue'> <b> Using Lists</b><font color='black'>

In [6]:
liste_1 = ["Mustafa", "Sedat", "Metehan", "Tulay"]

In [7]:
seri_1 = pd.Series(liste_1)
seri_1

0    Mustafa
1      Sedat
2    Metehan
3      Tulay
dtype: object

In [8]:
type(seri_1)

pandas.core.series.Series

In [9]:
seri_1.dtype

dtype('O')

In [11]:
arr1 = np.array([1.5, 3, "orkun"])
arr1

array(['1.5', '3', 'orkun'], dtype='<U32')

In [12]:
seri_2 = pd.Series(arr1)
seri_2

0      1.5
1        3
2    orkun
dtype: object

In [13]:
seri_3 = pd.Series([1.5, 3, 4.5]) #pandas series içinde string varsa her türlü object yapıyor. Diğer ihtimallerde farklı değerlendiriyor.
seri_3

0    1.5
1    3.0
2    4.5
dtype: float64

In [4]:
seri_3_3 = pd.Series([1.5, 3, 4.5, "Ali"])
seri_3_3

0    1.5
1      3
2    4.5
3    Ali
dtype: object

In [14]:
seri_4 = pd.Series([1.5, 3, 4.5]).astype(int)
seri_4

0    1
1    3
2    4
dtype: int32

In [15]:
seri_5 =pd.Series([1.5, 3, 4.5], index =  ["sıfır", "bir", "iki"])
seri_5

sıfır    1.5
bir      3.0
iki      4.5
dtype: float64

In [ ]:
seri_5 =pd.Series([1.5, 3, 4.5, False], index =  ["sıfır", "bir", "iki"]) #hata veri-index sayısı uyuşmuyor
seri_5

In [ ]:
seri_5 =pd.Series([1.5, 3, 4.5], index =  ["sıfır", "bir", "iki", "üç"]) #hata veri-index sayısı uyuşmuyor
seri_5

In [18]:
seri_6 =pd.Series([1.5, 3, 4.5], index =  ["sıfır", "bir", "bir"])
seri_6

sıfır    1.5
bir      3.0
bir      4.5
dtype: float64

### <font color='blue'> <b>Using NumPy Arrays</b><font color='black'>

In [19]:
arr2 = np.arange(1,13).reshape(3, 4)
arr2


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
pd.Series(arr2) #series tek boyutludur matris (2d)diziyi çeviremez.hata

In [21]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
pd.DataFrame(arr2)

0   1   2   3
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

### <font color='blue'> <b>Using Dictionaries</b><font color='black'>

In [23]:
dict_1 = {"Aslan" : 24, "Mustafa" : 35, "Şeyda" : 30}
dict_1

{'Aslan': 24, 'Mustafa': 35, 'Şeyda': 30}

In [24]:
pd.Series(dict_1)#keyleri index yaptı?

Aslan      24
Mustafa    35
Şeyda      30
dtype: int64

In [25]:
pd.Series(dict_1, index = ["aa", "bb", "cc"])

aa   NaN
bb   NaN
cc   NaN
dtype: float64

In [26]:
pd.Series(dict_1, index = ["Aslan", "Şeyda"])# key leri bulduğu sürece değerleri alır. 

Aslan    24
Şeyda    30
dtype: int64

In [27]:
pd.Series(dict_1, index = ["Aslan", "Şeyda", "İrem"])# key leri bulduğu sürece değerleri alır. 

Aslan    24.0
Şeyda    30.0
İrem      NaN
dtype: float64

In [58]:
dict_3 = {"Aslan": [24, 2000], "Mustafa": [35, 1989], "Şeyda": [30, 1994]}
dict_3

{'Aslan': [24, 2000], 'Mustafa': [35, 1989], 'Şeyda': [30, 1994]}

In [59]:
pd.Series(dict_3)

Aslan      [24, 2000]
Mustafa    [35, 1989]
Şeyda      [30, 1994]
dtype: object

In [28]:
dict_2 = {"name" : "İrem", "age" : 35, "Note" : 4.8}
dict_2

{'name': 'İrem', 'age': 35, 'Note': 4.8}

In [29]:
pd.Series(dict_2)

name    İrem
age       35
Note     4.8
dtype: object

In [30]:
pd.Series(dict_2, index =["name", "age", "Note", "job"] )

name    İrem
age       35
Note     4.8
job      NaN
dtype: object

### <font color='blue'> <b>Using Scalar Value</b><font color='black'>

Skalerler, skalerden oluşan liste veya demet gibi veri yapılarının aksine, bir tamsayı veya bool gibi bir veri birimini temsil eden tek değerlerdir.

Veri skaler bir değerse, bir dizin sağlanmalıdır.

In [31]:
pd.Series([10,10,10])

0    10
1    10
2    10
dtype: int64

In [6]:
pd.Series(10)

0    10
dtype: int64

In [5]:
pd.Series(10, index = [1, 2, 3])

0    10
dtype: int64

In [33]:
pd.Series(10, index = range(1,11))

1     10
2     10
3     10
4     10
5     10
6     10
7     10
8     10
9     10
10    10
dtype: int64

###  <font color='blue'> <b>Creating a series by combining two series</b><font color='black'>

In [34]:
seri_2

0      1.5
1        3
2    orkun
dtype: object

In [35]:
pd.concat([seri_2, seri_2])

0      1.5
1        3
2    orkun
0      1.5
1        3
2    orkun
dtype: object

In [36]:
seri_5

sıfır    1.5
bir      3.0
iki      4.5
dtype: float64

In [37]:
pd.concat([seri_2, seri_2, seri_5])

0          1.5
1            3
2        orkun
0          1.5
1            3
2        orkun
sıfır      1.5
bir        3.0
iki        4.5
dtype: object

## <font color='blue'> <b>Indexing and Slicing with Pandas Series</b><font color='black'>

In [8]:
seri_6 = pd.Series([1,2,3,4], index = ["Audi",  "BMW", "Mercedes", "Skoda"])
seri_6

Audi        1
BMW         2
Mercedes    3
Skoda       4
dtype: int64

In [39]:
seri_6[0] #series'lerde indexlemede index labeli göstermiyor, değeri gösteriyor.

C:\Users\iremtokuroglu\AppData\Local\Temp\ipykernel_19172\42352303.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  seri_6[0]


1

In [40]:
seri_6[2]

C:\Users\iremtokuroglu\AppData\Local\Temp\ipykernel_19172\2932481726.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  seri_6[2]


3

In [41]:
seri_6[1:3]#series'lerdeslicingde index labeli gösteriyor.

BMW         2
Mercedes    3
dtype: int64

In [42]:
seri_6["Audi"]

1

In [43]:
seri_6["Audi":"Skoda"] #son değer dahil, index eğer default indexleme değilse. dikkat et.

Audi        1
BMW         2
Mercedes    3
Skoda       4
dtype: int64

In [ ]:
seri_6["Bmw":]

In [44]:
seri_6["Audi":"Skoda":2]

Audi        1
Mercedes    3
dtype: int64

In [45]:
seri_6[["Audi", "Skoda"]]

Audi     1
Skoda    4
dtype: int64

In [9]:
seri_6["Audi", "Skoda"]

KeyError: 'key of type tuple not found and not a MultiIndex'

## <font color='blue'> <b>Basic Attributes & Methods of Series</b><font color='black'>

**SOME COMMON ATTRIBUTES** [Official Pandas API Document](https://pandas.pydata.org/docs/reference/api/pandas.Series.html)<br>

**Series.values:** Serinin değerlerinin Numpy dizisi (array) olarak döndürülmesini sağlar.

**Series.index:**  Serinin indekslerinin döndürülmesini sağlar.

**Series.dtype:**  Serinin veri tipini döndürür.

**Series.size:**   Serinin eleman sayısını döndürür.

**Series.shape:**  Serinin boyutunu döndürür.

**Series.ndim:**   Serinin boyut sayısını döndürür.

**Series.head():** Serinin ilk n adet elemanını döndürür.

**Series.tail():** Serinin son n adet elemanını döndürür.

**Series.sample():** Serinin random n adet elemanını döndürür.

**Series.describe():** Serinin istatistiksel özetini döndürür.

**Series.sort_index:** Seriyi indexlerine göre sıralar.

**Series.sort_values():** Seriyi değerlerine göre sıralar.

**Series.isnull():**      Serinin her bir elemanının null (None) olup olmadığını kontrol eder.

**Series.fillna():**      Null değerleri belirli bir değerle doldurur.
 
**Series.dropna():**      Null değerleri seriden çıkarır.

**Series.isin:**        Serideki öğelerin değerlerde yer alıp almadığını kontrol eder.

In [10]:
np.random.seed(34)
seri_7 = pd.Series(np.random.randint(1,51, 8))
seri_7

0    34
1    43
2    42
3    22
4     5
5    36
6     6
7    12
dtype: int32

In [11]:
seri_7.values #parantez yok, bir method değil attribute'tür.

array([34, 43, 42, 22,  5, 36,  6, 12])

In [12]:
seri_7.index

RangeIndex(start=0, stop=8, step=1)

In [48]:
seri_7.index[2:6]

RangeIndex(start=2, stop=6, step=1)

In [14]:
seri_8 = pd.Series([2,5], index = ["bir", "iki"])
seri_8

bir    2
iki    5
dtype: int64

In [15]:
seri_8.index[1:3]

Index(['iki'], dtype='object')

In [16]:
seri_8.index[0:]

Index(['bir', 'iki'], dtype='object')

In [17]:
seri_9 = pd.Series([2,5, 6, 7], index = ["bir", "iki", "üç", "dört"])
seri_9

bir     2
iki     5
üç      6
dört    7
dtype: int64

In [52]:
seri_9.index[1:3]

Index(['iki', 'üç'], dtype='object')

In [53]:
seri_8.index[1]

'iki'

In [18]:
seri_7.index[6] #6. indexi ne demek. indexler string olduğunda mantıklı

6

In [55]:
seri_7.dtype

dtype('int32')

In [56]:
seri_7.size

8