In [1]:
import numpy as np

# <font color='green'> <b>Various Built-in Methods</b><font color='black'>

## <font color='blue'> <b>rand & randn & randint </b><font color='white'>
**random.rand():** 0-1 aralığında uniform dağılıma sahip random float sayılar üretir.

**random.randn():** ortalama değeri 0 ve standart sapması 1 olan normal dağılıma sahip rastgele sayılar üretir.

**random.randint():** belirtilen aralıkta rastgele tamsayılar üretir. Bitiş dahil değil.

## rand

In [2]:
np.random.rand()

0.8539700165714992

In [3]:
np.random.rand(2,3)

array([[0.04782557, 0.85416231, 0.49622897],
       [0.93906686, 0.54205131, 0.5602524 ]])

# randn

In [4]:
np.random.randn()

-0.1822699731520635

In [5]:
np.random.randn(3,4)

array([[-0.128332  ,  1.14255793, -0.44051653, -1.45003103],
       [ 0.0395863 , -0.08027334, -0.56813745,  1.11481202],
       [ 0.74824169,  0.15127344, -0.09692179,  1.52624315]])

In [6]:
np.random.randn(3,4).mean()

-0.3857639731565082

In [8]:
np.random.randn(300,400).std()

0.9993939427960074

In [9]:
np.random.randn(300,400).mean()

-0.0037800868175381147

# randint ()

In [10]:
np.random.randint(10)

7

In [11]:
np.random.randint(4, 10)

9

In [12]:
np.random.randint(1, 100, 8) #tek boyut yani vektör.

array([50, 49, 58, 46, 68, 76, 84, 42])

In [13]:
np.random.randint(1, 100, size=(3,2))

array([[12, 22],
       [25, 37],
       [ 1, 42]])

In [22]:
np.random.seed(44)

In [23]:
np.random.randint(1, 100, size=(3,2))

array([[21, 36],
       [46, 60],
       [ 4, 97]])

In [24]:
np.random.randint(1, 100, size=(3,2))

array([[85,  4],
       [24, 56],
       [23, 90]])

## <font color='blue'> <b>max & argmax & min & argmin</b><font color='black'>

min(), bir dizinin içindeki en küçük değeri döndürür

max(), bir dizinin içindeki en büyük değeri döndürür

argmin(), bir dizinin içindeki en küçük değerin indeksini döndürür

argmax(), bir dizinin içindeki en büyük değerin indeksini döndürür

In [26]:
my_array_1 = np.random.randint(0, 50, 12)
my_array_1

array([ 3,  7,  3, 35, 38, 45, 36,  1, 14, 39, 36, 29])

In [27]:
my_array_1.min()

1

In [31]:
my_array_1.argmin() # index değerini döndürür.

7

In [28]:
my_array_1.max()

45

In [32]:
my_array_1.argmax() # index değerini döndürür.

5

## <font color='blue'> <b>size</b><font color='white'>
Bir dizideki toplam eleman sayısı

2x3'lük bir matris için size=6

In [42]:
bb=np.random.randint(50, size =(4,5))
bb

array([[21, 19, 32, 10, 36],
       [41, 31, 18,  8, 29],
       [ 8, 10, 22, 16,  8],
       [18, 28, 29,  1, 12]])

In [43]:
bb.size

20

In [2]:
aa = my_array_1.reshape(-1, 4)
aa

NameError: name 'my_array_1' is not defined

In [39]:
aa.size

12

In [41]:
len(aa) #satır sayısını getirir.

3

## <font color='blue'> <b>itemsize</b><font color='white'>
    
itemsize(), NumPy dizisinin her bir elemanının bellekte kaç byte kapladığını gösterir. 

Bu özellik, NumPy dizisinin veri tipine (dtype) bağlıdır ve bu veri tipinin boyutuna göre değişir.

itemsize(), bir NumPy dizisinin bellekte kapladığı toplam alanı hesaplamak için de kullanılabilir. Bu hesaplama, dizinin eleman sayısının itemsize() ile çarpımı ile yapılabilir.

float32 tipi 32 bit (4 byte) bellek kullanır ve yaklaşık 7 basamak hassasiyetle ondalık sayıları temsil edebilir. 

32 bitlik bir sayı, 2^32 farklı sayıyı ifade edebilir.

float64 tipi ise 64 bit (8 byte) bellek kullanır ve yaklaşık 15-16 basamak hassasiyetle ondalık sayıları temsil edebilir

64 bitlik bir sayı, 2^64 farklı sayıyı ifade edebilir.

In [1]:
aa + 500

NameError: name 'aa' is not defined

In [45]:
aa.itemsize #her bir değerin boyutunu gösterir. byte cinsinden gösterir.

4

In [46]:
aa.dtype

dtype('int32')

## <font color='blue'> <b>copy() </b><font color='white'>
copy(), Numpy dizilerinde bir kopya oluşturmak için kullanılır.

Bu fonksiyon, orijinal dizinin aynısını oluşturur ancak bu kopya bağımsızdır. Yani, kopya dizisi üzerinde yapılan herhangi bir değişiklik, orijinal diziyi etkilemez ve orijinal dizi üzerinde yapılan değişiklikler de kopya dizisini etkilemez.    

In [49]:
my_array2 = np.arange(1,17).reshape(-1,4)
my_array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [50]:
copyarray = my_array2.copy()

In [51]:
copyarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
cc = copyarray #böyle yaptığında copyarraydeki bir değişiklik bb'yi de etkiler.bir dataframe'de daha hiç başlamadan bir kopyasını oluşturmakta fayda var.

## <font color='blue'> <b>transpose() </b><font color='white'>
transpose() fonksiyonu, NumPy dizilerinin boyutlarını değiştiren bir işlevdir. Özellikle matrislerin transpozunu almak için kullanılır.

Bir matrisin transpozunu almak, matrisin satırlarını sütunlarına, sütunlarını da satırlarına dönüştürür.

In [52]:
copyarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [54]:
copyarray.transpose()

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [55]:
copyarray.T #transpose kısa yolu. transpose kalıcı değişiklik yapmaz.

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [56]:
copyarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

# <font color='green'> <b>Concatenation of the Arrays</b><font color='white'>
concatenate() fonksiyonu, iki veya daha fazla diziyi birleştirmek için kullanılır. 

Fonksiyonun ilk parametresi birleştirilecek dizilerin bir listesidir. 

İkinci parametre ise, birleştirme işleminin hangi eksen veya boyuta göre yapılacağını belirten bir parametredir.

Örneğin, axis=0 parametresi, dizilerin satır bazında (dikey birleştirme) birleştirilmesini, axis=1 parametresi ise sütun bazında (yatay birleştirme) birleştirilmesini sağlar.

In [ ]:
#axis 0 satırları axis 1 sütunları ifade eder.

In [58]:
x = np.arange(1,7)
x

array([1, 2, 3, 4, 5, 6])

In [60]:
y = np.arange (7,13)
y

array([ 7,  8,  9, 10, 11, 12])

In [62]:
xy = np.concatenate((x,y)) #default axis değeri 0, tekboyutta yan yana birleştirir. 2 boyutta axisi baz alır.
xy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [66]:
xy = np.concatenate((x,y), 1) #tek boyutlu değerlerde axis 1 kkullanılamaz.
xy

AxisError: axis 1 is out of bounds for array of dimension 1

In [68]:
a = np.array([[1, 2],[3, 4]])
a

array([[1, 2],
       [3, 4]])

In [69]:
b = np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [70]:
ab = np.concatenate((a,b)) 
ab

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [71]:
ab = np.concatenate((a,b), 1) 
ab

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [72]:
ab = np.concatenate((a,b), 2) 
ab

AxisError: axis 2 is out of bounds for array of dimension 2

In [73]:
c = np.array([[1, 2],[3, 4]])
c

array([[1, 2],
       [3, 4]])

In [74]:
d = np.array([[5,6],[7,8], [9,10]])
d

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [77]:
cd = np.concatenate((c,d)) 
cd

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [79]:
cd = np.concatenate((c,d), axis = 1) 
cd

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

In [78]:
np.concatenate((c,d), None) #none ifadesi tek boyuta indirerek birleştirir.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# <font color='green'> <b>Splitting of the Arrays</b><font color='white'>
[numpy.split 01](https://www.w3resource.com/numpy/manipulation/split.php),
[numpy.split 02](https://sparkbyexamples.com/numpy/numpy-split-array/),
[numpy.split 03](https://numpy.org/doc/stable/reference/generated/numpy.array_split.html),
[numpy.split 04](https://www.w3schools.com/python/numpy/numpy_array_split.asp) 
**split():**, numpy dizisini belirtilen eksende eşit parçalara bölmek için kullanılır.

**array_split():** fonksiyonu, NumPy'da bir diziyi belirtilen sayıda eşit olmayan parçalara bölmek için kullanılır. Bu fonksiyon, diğer bölme fonksiyonlarından (hsplit, vsplit gibi) farklı olarak belirli bir eksende değil, kullanıcının belirttiği sayıda parçaya böler.

***vsplit():** NumPy'da bir diziyi satırlar üzerinden birden çok parçaya ayırmak için kullanılır.

***hsplit():** NumPy'da bir diziyi sütunlar üzerinden birden çok parçaya ayırmak için kullanılır. Temel olarak, bir matrisi sütunlarını kullanarak belirtilen indekslerde böler.

In [80]:
my_array3 = np.arange(1,9)
my_array3

array([1, 2, 3, 4, 5, 6, 7, 8])

In [81]:
np.split(my_array3, 4)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

In [82]:
np.split(my_array3, 5)

ValueError: array split does not result in an equal division

In [83]:
np.array_split(my_array3, 5)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7]), array([8])]

In [84]:
np.split(my_array3, [5])#5. indexe kadar, 5 dahil değil böler, kalanı ayrı olarak yazar.

[array([1, 2, 3, 4, 5]), array([6, 7, 8])]

In [86]:
aa = np.arange(1,18)
aa

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [87]:
np.split(aa, [5])

[array([1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])]

In [88]:
np.split(aa, [5, 8])

[array([1, 2, 3, 4, 5]),
 array([6, 7, 8]),
 array([ 9, 10, 11, 12, 13, 14, 15, 16, 17])]

In [89]:
my_array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [90]:
np.split(my_array2, [1]) #1. indexe kadarki kısmı böldü. kalanı da ayırdı. axis default 0 olduğu için

[array([[1, 2, 3, 4]]),
 array([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [3]:
np.split(my_array2, [1], axis =1) #1. indexe kadarki kısmı böldü. kalanı da ayırdı. axis 1 olduğu için.

NameError: name 'np' is not defined

In [92]:
np.split(my_array2,4)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]

In [93]:
np.split(my_array2,4, axis =1)

[array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]]),
 array([[ 4],
        [ 8],
        [12],
        [16]])]

In [ ]:
#vsplit ve hspliti kullanırken axis belirtmezsin sadece.ekstra bir şey değil yani.

# <font color='green'> <b>Sorting of the Arrays</b><font color='white'>
[numpy.sort 01](https://www.w3schools.com/python/numpy/numpy_array_sort.asp),
[numpy.sort 02](https://sparkbyexamples.com/python/numpy-sort-arrays-examples/),
[numpy.sort 03](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.sort.html),
[numpy.sort 04](https://www.geeksforgeeks.org/how-to-sort-a-numpy-array-python/)
sort(), numerik ya da alfabetik array elemanlarını, numerik veya alfabetik sıralarına göre sıralamasını yapar.  

In [ ]:
#her satırı kendi içinde sıralama yapar.

In [94]:
bb = np.array([2, 4, 1, 5, 3])
bb

array([2, 4, 1, 5, 3])

In [95]:
np.sort(bb) #kalıcı değişiklik yamaz fonk. çünkü

array([1, 2, 3, 4, 5])

In [96]:
bb

array([2, 4, 1, 5, 3])

In [ ]:
bb.sort() #kalıcı değişiklik yapar. method çünkü

In [107]:
my_arr4 = np.random.randint(5, 50, (3,3))
my_arr4

array([[27, 18, 35],
       [10, 21,  9],
       [39, 16, 45]])

In [108]:
np.sort(my_arr4, axis = 1) #sütunlar bazında sıralama yapar.  satırı sabit tutarken sütundaki verileri sıralar.

array([[18, 27, 35],
       [ 9, 10, 21],
       [16, 39, 45]])

In [109]:
np.sort(my_arr4, axis = 0) #satırlar bazında sıralama yapar.  sütunu sabit tutarken satırdaki verileri sıralar.

array([[10, 16,  9],
       [27, 18, 35],
       [39, 21, 45]])

In [110]:
np.sort(my_arr4)

array([[18, 27, 35],
       [ 9, 10, 21],
       [16, 39, 45]])

In [111]:
np.sort(my_arr4, axis = None) #tek boyuta çevirip tüm verileri sıralıyor.

array([ 9, 10, 16, 18, 21, 27, 35, 39, 45])

# axis ile ilgili örnek

In [113]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [114]:
arr1.ndim

1

In [115]:
arr1.shape

(3,)

In [116]:
np.concatenate((arr1, arr2))

array([1, 2, 3, 4, 5, 6])

In [117]:
arr3 = np.array([[1,2], [3,4]])
arr4 = np.array([[5,6], [7,8]])

In [118]:
arr3.ndim

2

In [119]:
arr3.shape

(2, 2)

In [121]:
np.concatenate((arr3, arr4), axis = 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [124]:
arr3_4 = np.concatenate((arr3, arr4), axis = 0)
arr3_4

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [125]:
np.sort(arr3_4, axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [131]:
z = np.array([[75], [1], [28], [46]])

In [4]:
np.sort(z, axis=0)

NameError: name 'np' is not defined