# <font color='green'> <b>Importing Libraries </b><font color='black'>

[Numpy Source 01](https://numpy.org/),
[Numpy Source 02](https://www.w3schools.com/python/numpy/numpy_intro.asp),
[Numpy Source 03](https://www.geeksforgeeks.org/python-numpy/),
[Numpy Source 04](https://scipy-lectures.org/intro/numpy/array_object.html),
[Numpy Source 05](https://www.javatpoint.com/numpy-tutorial),
[Numpy Source 06](https://medium.com/analytics-vidhya/introduction-to-numpy-16a6efaffdd7)

- **NumPy**, Python Standard Library'de yer almayan bir modüldür, python yüklemesiyle önceden yüklenmiş olarak gelmez.

- NumPy modülünü import etmeden önce, onu Python'ın pip aracıyla install etmemiz gerekmektedir. -pip install numpy-

- **pip** aracı, Standard Library'de bulunmayan modülleri ya da paketleri dışarıdan install etmemize olanak tanır.

- Ancak Anaconda'yı kurduğunuzda, temel Python diline ek olarak Numpy dahil birçok kütüphane önceden yüklenmiş olarak gelir.

In [2]:
# pip install numpy

In [6]:
import numpy as np

## <font color='blue'> <b>ndim & ndmin  </b><font color='white'>
**ndim**:
- Bir NumPy array'inin boyutunu gösterir.

**ndmin**:
- ndmin, "minimum dimension" ifadesinin kısaltmasıdır ve Türkçede "minimum boyut" anlamına gelir.
- np.array() fonksiyonunda bu parametreyi kullanarak, oluşturulacak dizinin en az kaç boyutlu olması gerektiğini belirtiriz.
- Eğer verilen veri belirtilen boyutun altındaysa, eksik boyutlar otomatik olarak eklenir. 
- Bu, daha yüksek boyutlu bir diziyle işlem yapmak istendiğinde, fakat verinin bu boyutta olmadığında kullanışlıdır.

In [4]:
arr0 = np.array(5) #liste gibi vermezsen bu şekilde verirsen bu scalar'dır. boyutu 0'dır.

In [5]:
arr0.ndim #açılımı number of dimension gibi

0

In [6]:
arr1 = np.array([1,2])
arr1

array([1, 2])

In [7]:
arr1.ndim

1

In [1]:
my_list = range (0,24)
my_list

range(0, 24)

In [9]:
my_array = np.array(my_list)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [10]:
my_array.ndim

1

In [11]:
my_array.shape

(24,)

In [12]:
my_array2 = np.array(my_list, ndmin=2)
my_array2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23]])

In [13]:
my_array2.ndim

2

In [14]:
my_array2.shape

(1, 24)

## <font color='blue'> <b>dtype & astype() </b><font color='white'>

**dtype**:
- dtype (data type), bir ndarray'de saklanan verinin türünü belirtir.
- Bir ndarray oluştururken dtype parametresi kullanılarak veri tipi belirtilebilir. Eğer belirtilmezse, NumPy verilere uygun bir veri tipi seçer.


**astype()**:
- astype() bir ndarray metodudur ve mevcut bir ndarray'nin veri tipini değiştirmek için kullanılır.
- Bu metod, verinin yeni bir kopyasını oluşturarak yeni veri tipine dönüştürür. Orijinal dizi değişmez.

In [15]:
my_int = np.array([1,2,3])
my_int

array([1, 2, 3])

In [16]:
my_int.dtype

dtype('int32')

In [17]:
my_int = np.array([1,2,3], dtype = "int64")
my_int

array([1, 2, 3], dtype=int64)

In [18]:
my_float = np.array ([1, 2, 3.2, 4])
my_float

array([1. , 2. , 3.2, 4. ])

In [19]:
my_float.dtype

dtype('float64')

In [20]:
my_string = np.array([1, 2, 3, 4.5, "a"])
my_string

array(['1', '2', '3', '4.5', 'a'], dtype='<U32')

In [21]:
my_string = np.array([1, 2, 3, 4.5, "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"])
my_string

array(['1', '2', '3', '4.5', 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'],
      dtype='<U32')

In [22]:
my_string.dtype

dtype('<U32')

In [23]:
my_float2 = np.array([1,2,3], dtype = "float")#dtype hem bir attribute hem bir parametredir.
my_float2

array([1., 2., 3.])

In [24]:
my_float2.astype("int") #geçicidir değişkene atmazsan eski halini verir.

array([1, 2, 3])

In [25]:
my_float2

array([1., 2., 3.])

In [26]:
newint = my_float2.astype(int)
newint

array([1, 2, 3])

In [27]:
newint.dtype #demek ki int 32 default değer.

dtype('int32')

In [28]:
newbool = my_float2.astype(bool)
newbool

array([ True,  True,  True])

## <font color='blue'> <b>resize() </b><font color='white'>

**resize()**
- ndarray nesnesinin boyutunu yeniden şekillendirmek için kullanılır. 

- Bu yöntem, ndarray nesnesinin boyutunu değiştirir ve yeni boyutlara uygun olarak verileri değiştirir. 

In [29]:
arr = np.array([[1, 3, 2], [4, 6, 5]])
arr

array([[1, 3, 2],
       [4, 6, 5]])

In [30]:
np.resize(arr, (2,2)) #arr üzerinde değişiklik yapmaz. söylediğin boyuta geçtiğinde fazla veri varsa siler az veri varsa baştan başlayarak doldurur.

array([[1, 3],
       [2, 4]])

In [31]:
arr

array([[1, 3, 2],
       [4, 6, 5]])

In [32]:
np.resize(arr, (5,2))

array([[1, 3],
       [2, 4],
       [6, 5],
       [1, 3],
       [2, 4]])

In [33]:
np.resize(arr, (7,9))

array([[1, 3, 2, 4, 6, 5, 1, 3, 2],
       [4, 6, 5, 1, 3, 2, 4, 6, 5],
       [1, 3, 2, 4, 6, 5, 1, 3, 2],
       [4, 6, 5, 1, 3, 2, 4, 6, 5],
       [1, 3, 2, 4, 6, 5, 1, 3, 2],
       [4, 6, 5, 1, 3, 2, 4, 6, 5],
       [1, 3, 2, 4, 6, 5, 1, 3, 2]])

# <font color='green'> <b>Create Arrays from Built-in Methods</b><font color='black'>
[Create Array Source 01](https://www.w3resource.com/numpy/array-creation/),
[Create Array Source 02](https://www.geeksforgeeks.org/numpy-arrange-in-python/?ref=lbp),
[Create Array Source 03](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.astype.html),
[Create Array Source 04](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.resize.html),
[Create Array Source 05](https://www.geeksforgeeks.org/numpy-arrange-in-python/?ref=lbp),
[Create Array Source 06](https://sparkbyexamples.com/numpy/ways-to-create-numpy-array/) &
[Create Array Source 07](https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/FunctionsForCreatingNumpyArrays.html)

[Numpy Array Video Source 02](https://www.youtube.com/watch?v=8Mpc9ukltVA&t=2s) &
[Numpy Array Video Source 03](https://www.youtube.com/watch?v=Qgh1vjmaj44) 

## <font color='blue'> <b>arange() </b><font color='white'>
Python’daki range() fonksiyonuna benzer. 

Belirtilen başlangıç değerinden başlayıp, her seferinde adım sayısı kadar arttırarak ,bitiş değerine kadar olan sayıları bulunduran bir numpy dizisi dödürür.

Not: Bitiş değerinin diziye dahil edilmediğine dikkat edelim.

In [34]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [36]:
np. arange(0, 10, 2.2) #range ile nerdeyse birebir aynı ancak arange float sayılarla çalışır.

array([0. , 2.2, 4.4, 6.6, 8.8])

In [37]:
np. arange(0, 10.2, 2)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [38]:
np. arange(0, 10, -2.2) #start ve step arasında sayı bulunmadığı için boş array döndürdü.


array([], dtype=float64)

In [39]:
np. arange(10, 0, -2.2)

array([10. ,  7.8,  5.6,  3.4,  1.2])

## <font color='blue'> <b>linspace() </b><font color='white'>
Verilen başlangıç ve bitiş değerleri arasında, belirtilen sayıda eşit aralıklı değerlerden oluşan bir numpy dizisi oluşturur.

Bu fonksiyon, özellikle grafik çizme ve veri analizi gibi durumlarda yararlıdır.


In [40]:
np.linspace(1, 10, 4) # 1 ile 10 arasında 4 tane  sayı oluştur. 1 ve 10 dahildir.bunların aralığı eşittir.

array([ 1.,  4.,  7., 10.])

In [41]:
np.linspace(1, 10, 5) 

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [42]:
np.linspace(1, 20) #default 50dir.50 sayı üretir eğer hiçbişey yazmazsan.

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [43]:
np.linspace(1, 20, dtype=int)

array([ 1,  1,  1,  2,  2,  2,  3,  3,  4,  4,  4,  5,  5,  6,  6,  6,  7,
        7,  7,  8,  8,  9,  9,  9, 10, 10, 11, 11, 11, 12, 12, 13, 13, 13,
       14, 14, 14, 15, 15, 16, 16, 16, 17, 17, 18, 18, 18, 19, 19, 20])

In [44]:
np.linspace(1, 20, 4, endpoint=True) #defaultu zaten true olduğu için stop noktasını da alıyor.

array([ 1.        ,  7.33333333, 13.66666667, 20.        ])

In [45]:
np.linspace(1, 20, 4, endpoint=False) #defaultu zaten true olduğu için stop noktasını da alıyor.

array([ 1.  ,  5.75, 10.5 , 15.25])

In [46]:
np.linspace(1, 20, 10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [47]:
np.linspace(1, 20, 10, retstep = True ) #retstep parametresi true olursa sonda artış miktarını da gösteriyor.

(array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
        11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ]),
 2.111111111111111)

In [65]:
np.linspace(1, 10, 4, retstep = True )

(array([ 1.,  4.,  7., 10.]), 3.0)

## <font color='blue'> <b>logspace() </b><font color='white'>
logspace() logaritmik aralıklarda bir dizi oluşturur. 

logspace() fonksiyonu, linspace() fonksiyonuna benzer şekilde çalışır, ancak aralıklar logaritmik olarak hesaplanır.

Logspace : Başlangıç değeri 10a ,bitiş değeri değeri 10b olan n elemanlı ve elemanları arasındaki katları eşit olan bir dizi oluşturur.

In [48]:
#linspace ile neredeyse hemen hemen aynı.logaritmik meslelerle alakalı.

In [49]:
np.logspace(2,3, num=5) #10^2 ve 10^3 ten gelir.Aralıklar da logaritmik olarak ilerliyor dikkat et.

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

## <font color='blue'> <b>zeros & zeros_like() </b><font color='white'>
**zeros():** Belirtilen satır ve sütuna sahip 0'lardan oluşan bir matris döndürür.

**zeros_like():** Verilen bir diziyle aynı şekil ve türde, ancak tüm elemanları 0 olan bir dizi oluşturur.
   

In [50]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
arr2 = np.arange(1, 13).reshape(4,3)
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [52]:
np.zeros_like(arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [53]:
np.zeros_like(arr2, dtype=bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

## <font color='blue'> <b>ones & ones_like() </b><font color='white'>
**ones:** Belirtilen satır ve sütuna sahip 1'lerdan oluşan bir matris döndürür.

**ones_like:** Verilen bir diziyle aynı şekil ve türde, ancak tüm elemanları 1 olan bir dizi oluşturur.
   

In [54]:
#zeros ve zeroslikela birebir aynı ancak 1'lerden oluşturuyor arrayi

In [55]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [56]:
np.ones_like(arr2)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [57]:
np.ones_like(arr2) * 4

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [66]:
[1, 1, 1, 1] * 4

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [58]:
np.ones_like(arr2, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## <font color='blue'> <b>eye() </b><font color='white'>
- Bu fonksiyon, belirtilen boyutta bir birim matris (identity matrix) oluşturur. 
- Birim matriste, ana köşegen üzerindeki elemanlar 1'dir ve diğer tüm elemanlar 0'dır.

In [59]:
np.eye(4) #köşegeni birlerden oluşan kare yani satır ve sütunu birbrine eşit matris oluşturur.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [60]:
np.eye(6, k = 1) #x ekseninde öteler köşegeni, k parametresine verdiğin değer kadar.

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]])

## <font color='blue'> <b>full() & full_like() </b><font color='white'>
**full():** Belirtilen şekil ve değere sahip bir dizi oluşturur.

**full_like():** Verilen bir dizinin şekli ve türüne sahip, ancak belirtilen değerle doldurulmuş bir dizi oluşturur.

In [7]:
np.full((2,5), 7) # 2ye 5lik matris oluştur içini 7lerle doldur.full likea örnek yz örnek vermemişiz derste.

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [9]:
np.full((2,5), np.nan)

array([[nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan]])

In [63]:
aa = np.full((2,5), np.nan)
aa

array([[nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan]])

In [64]:
aa.dtype #yani nan default olarak float datatype'ındadır.

dtype('float64')