In [2]:
import numpy as np

# <font color='green'> <b>Numpy Indexing & Selection</b><font color='white'>
[INDEXING & SLICING Source 01](https://jakevdp.github.io/PythonDataScienceHandbook/03.02-data-indexing-and-selection.html),
[INDEXING & SLICING Source 02](https://www.kite.com/python/answers/how-to-select-an-element-by-index-from-a-numpy-array-in-python),
[INDEXING & SLICING Source 03](https://www.w3schools.com/python/numpy/numpy_array_indexing.asp),
[INDEXING & SLICING Source 04](https://www.pluralsight.com/guides/working-numpy-arrays-indexing-slicing-guide),
[INDEXING & SLICING Source 05](https://www.brainstobytes.com/hands-on-numpy-iii-indexing-and-slicing/),
[INDEXING & SLICING Source 06](https://www.geeksforgeeks.org/numpy-indexing/),
[INDEXING & SLICING Source 07](https://www.tutorialspoint.com/numpy/numpy_advanced_indexing.htm),
[INDEXING & SLICING Source 08](https://towardsdatascience.com/numpy-indexing-explained-c376abb2440d),
[INDEXING & SLICING Video Source 01](https://www.pythoninformer.com/python-libraries/numpy/index-and-slice/),
[INDEXING & SLICING Video Source 02](https://www.youtube.com/watch?v=9nbBTaz2qXI),
[INDEXING & SLICING Video Source 03](https://www.youtube.com/watch?v=E1OFcMnU40o)
    
NumPy dizilerinde belirli bir elemana erişmek için, dizi adını takiben köşeli parantez içinde ilgili elemanın indeks numarasını belirtiriz.Örn; myarr[indexno]

İndeks numaraları 0'dan başlar, yani ilk elemanın indeksi 0'dır ve diğer elemanların indeks numaraları sırasıyla 1, 2, 3, gibi artar.

Ayrıca negatif indeksleme de kullanabiliriz. Negatif indeksleme, NumPy dizilerinde sondan başlayarak elemanlara erişmek için kullanılır. Son elemanın indeksi -1'dir ve önceki elemanların indeksleri sırayla -2, -3, gibi devam eder.

2 boyutlu NumPy dizilerinde, belirli bir elemana erişmek için satır ve sütun numaralarını kullanırız. Bu şekilde erişim için myarr[satırno, sütunno] formatı kullanılır.

3 boyutlu NumPy dizilerinde ise, elemana erişmek için derinlik, satır ve sütun numaralarını kullanırız. Yani erişim için myarr[derinlikno, satırno, sütunno] formatı kullanılır.

## <font color='blue'> <b>Bracket Indexing & Selection</b><font color='white'>
Bir dizinin bir veya birkaç öğesini seçmenin en basit yolu, python listelerindeki gibi yapılır.

In [3]:
arr1 = np.arange (12,21)
arr1

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr1[5]

17

In [5]:
arr1[-2]

19

In [6]:
arr1[1:4]

array([13, 14, 15])

In [7]:
arr1[::2]

array([12, 14, 16, 18, 20])

## <font color='blue'> <b>Indexing a 2D Array (Matrices)</b><font color='black'>
    
[SOURCE01](https://medium.com/@msjahid/numpy-array-indexing-slicing-23b70abb8433),
[SOURCE02](https://iq.opengenus.org/2d-array-in-numpy/)

In [8]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr_2d[2,1] #arr_2d[2][1] ifadesi de çalışıyor.

8

In [15]:
arr_2d[1::,1::] #ilk ifade satırlarda nerden başlayıp nereye geleceğini söylüyor. ikinci ifade ise sütunlarda nerden başlayıp nereye gelecğini gösteriyor.

array([[5, 6],
       [8, 9]])

## <font color='blue'> <b>Slicing a 2D Array (Matrices)</b><font color='black'>
    
[SOURCE1](https://stackoverflow.com/questions/16096753/python-array-slicing-how-can-2d-array-slicing-be-implemented)
[SOURCE2](https://scipy-lectures.org/intro/numpy/array_object.html)
[SOURCE3](http://cs-tklab.na-inet.jp/~tkouya/python/scipy-lectures/intro/numpy/array_object.html)   

In [17]:
arr2 = np.arange(0,36).reshape(6,-1)
arr2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [18]:
arr2[:,::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28],
       [30, 32, 34]])

In [20]:
arr2[2:4,2:5]

array([[14, 15, 16],
       [20, 21, 22]])

In [21]:
arr2[2:5:2,:5:2]

array([[12, 14, 16],
       [24, 26, 28]])

## <font color='blue'> <b>Fancy Indexing</b><font color='white'>
    
Fancy Indexing, NumPy dizilerinde, bir veya daha fazla koşula veya belirtilen indeksler listesine göre dizideki belirli elemanlara erişmek için kullanılan bir indeksleme yöntemidir.

Bu yöntemde, köşeli parantez içinde bir liste veya dizi kullanarak, ilgili dizinin belirli elemanlarına erişebilirsiniz. Bu indeksleme yöntemi, normal indeksleme yöntemlerine göre daha esnek ve güçlüdür.

[SOURCE 01](https://jakevdp.github.io/PythonDataScienceHandbook/02.07-fancy-indexing.html#:~:text=Fancy%20indexing%20is%20conceptually%20simple,random.),
[SOURCE 02](https://notes.tahamaddam.com/coding/numpy/numpy-fancy-indexing), 
[SOURCE 03](https://stackoverflow.com/questions/52485840/numpy-fancy-indexing-with-tuples?rq=1),
[VIDEO SOURCE](https://www.youtube.com/watch?v=WpXH4PzDtYA)

In [22]:
arr2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [24]:
arr2[(2, 4, 5),(0,2,4)] #bu bir fancy

array([12, 26, 34])

In [25]:
arr2[2:, (1,3,5)] #ama bu klasik yöntem ve fancy'nin birleştirilmişi

array([[13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35]])

In [26]:
arr2[(1,3,5), 2:]

array([[ 8,  9, 10, 11],
       [20, 21, 22, 23],
       [32, 33, 34, 35]])

## <font color='blue'> <b>Selection on a Condition</b><font color='black'>

In [31]:
np.random.seed(40)
arr3 = np.random.randint(1,50, size = (3,4))
arr3

array([[ 7, 28,  8, 38],
       [ 2, 13,  8, 20],
       [32, 11, 20, 28]])

In [33]:
arr3 > 20

array([[False,  True, False,  True],
       [False, False, False, False],
       [ True, False, False,  True]])

In [35]:
arr3[arr3 > 20]

array([28, 38, 32, 28])

In [36]:
arr3[1] > 20

array([False, False, False, False])

In [37]:
arr3[arr3[1] > 20]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 3 but corresponding boolean dimension is 4

In [40]:
arr4 = np.arange (1,51)
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [41]:
arr4 %2 == 0

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True])

In [42]:
arr4[arr4 %2 == 0] #çift sayıları ayıklar

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

In [44]:
arr4[(arr4 %2 == 0) == False] #tek sayıları ayıklar

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [45]:
arr2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [46]:
mask = np.array([1, 0, 1, 0, 0,1],dtype =bool)

In [47]:
arr2[mask, 2]

array([ 2, 14, 32])

# <font color='green'> <b>Broadcasting</b><font color='black'>

[SOURCE01](https://numpy.org/doc/stable/user/basics.broadcasting.html),
[SOURCE02](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html),
[SOURCE03](https://towardsdatascience.com/broadcasting-in-numpy-58856f926d73),
[SOURCE04](https://towardsdatascience.com/a-numpy-affair-broadcasting-ead20d9661f),
[SOURCE05](https://data-flair.training/blogs/numpy-broadcasting/),
[SOURCE06](https://stackoverflow.com/questions/47309818/when-broadcasting-is-a-bad-idea-numpy)
[SOURCE07](https://www.pluralsight.com/guides/broadcasting-numpy-arrays-arithmeetic-operations), 
[SOURCE08](https://www.geeksforgeeks.org/python-broadcasting-with-numpy-arrays/), 
[SOURCE09](https://www.askpython.com/python-modules/numpy/numpy-broadcasting), 
[SOURCE10](https://stackoverflow.com/questions/32832923/numpy-what-is-broadcasting), 
[SOURCE11](https://stackoverflow.com/questions/61090539/how-can-i-use-broadcasting-with-numpy-to-speed-up-this-correlation-calculation), 
[SOURCE12](https://stackoverflow.com/questions/68185016/numpy-broadcasting-two-arrays-of-different-shape-to-matrix), 
[SOURCE13](https://stackoverflow.com/questions/50569344/broadcasting-using-numpys-sum-function)


Broadcasting, farklı şekillerdeki (shape) NumPy dizileri üzerinde aritmetik işlemler yapmak için kullanılan bir özelliktir.

Bu özellik, işlem yapmak için iki dizinin şekillerinin tam olarak eşleşmesi gerektiği durumlarda, NumPy'nin işlemi otomatik olarak yürüterek daha esnek bir şekilde işlem yapılmasını sağlar.

Broadcasting işlemi, daha küçük boyutlu bir dizi ile daha büyük boyutlu bir dizi arasında gerçekleştirilir. 

Bu işlemde, daha küçük boyutlu dizi, diğer diziye uyarlanarak işlem yapılabilir hale getirilir.

# <font color='green'> <b>Arithmetic Operations & Universal Array Functions</b><font color='black'>

Arithmetic Operations, NumPy dizileri üzerinde aritmetik işlemler yapmak için kullanılan işlevlerdir. 

Matematiksel işlemleri vektörize ederek, for döngüleri gibi yavaş işlemlerden kaçınarak hızlı ve etkili hesaplamalar yapılmasını sağlar.

Toplama, çıkarma, çarpma, bölme, üs alma, karekök alma ve benzeri birçok aritmetik işlemi destekler. 

Farklı boyutlarda ve şekillerdeki NumPy dizileri üzerinde uygulanabilir.

Universal Array Functions (Ufuncs)(Evrensel Dizi Fonksiyonları), NumPy dizileri üzerinde hızlı ve etkili matematiksel işlemleri yapmak için kullanılan işlevlerdir. Bu işlevler, özellikle büyük veri setleri üzerinde hızlı hesaplamalar yapmak için tasarlanmıştır.

Ufuncs işlevleri, matematiksel işlemleri vektörize etmek için kullanılabilir. Bu sayede, for döngüleri ve benzeri işlemlerle uğraşmadan, NumPy dizilerinde hızlı işlemler gerçekleştirmek mümkündür.

NumPy Ufuncs işlevleri arasında, trigonometrik işlemler (sin, cos, tan vb.), logaritmik işlemler (log, exp vb.), aritmetik işlemler (toplama, çıkarma, çarpma, bölme vb.) gibi birçok işlev bulunur. Bu işlevler, farklı boyutlarda ve şekillerdeki NumPy dizileri üzerinde kullanılabilir.

[Universal Array Functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html)


In [48]:
arr1

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [49]:
arr1 + arr1

array([24, 26, 28, 30, 32, 34, 36, 38, 40])

In [50]:
np.add(arr1, arr1)

array([24, 26, 28, 30, 32, 34, 36, 38, 40])

In [51]:
arr1 - 3

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17])

In [53]:
np.subtract(arr1, 3)

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17])

In [54]:
np.subtract( 3, arr1)

array([ -9, -10, -11, -12, -13, -14, -15, -16, -17])

# <font color='green'> <b>Statistical Calculations</b><font color='black'>

NumPy, veriler üzerinde istatistiksel hesaplamalar yapmak için kullanılan bir kütüphanedir. 

Verilerin ortalaması, medyanı, standart sapması, varyansı, korelasyon katsayısı, kovaryans, histogram, maksimum ve minimum değerler gibi birçok istatistiksel hesaplama işlemi yapılmasını sağlar.

Veri setlerinin hızlı bir şekilde analiz edilmesine yardımcı olur. Ayrıca, verilerin dağılımı hakkında bilgi edinmek, anormal değerlerin tespit edilmesi, verilerin normal dağılım gösterip göstermediğini kontrol etmek gibi amaçlar için de kullanılır.

[SOURCE01](https://data-flair.training/blogs/numpy-statistical-functions/),
[SOURCE02](https://numpy.org/doc/stable/reference/routines.statistics.html), 
[SOURCE03](https://www.tutorialspoint.com/numpy/numpy_statistical_functions.htm), 
[SOURCE04](https://www.i2tutorials.com/numpy-tutorial/numpy-statistical-functions/), 
[SOURCE05](https://towardsdatascience.com/use-numpy-for-statistics-and-arithmetic-operations-in-2020-2e157b784df4), 
[SOURCE06](https://cloudxlab.com/assessment/displayslide/2509/numpy-mathematical-and-statistical-functions-on-numpy-arrays), [SOURCE07](https://stackoverflow.com/questions/63888139/calculating-some-statistics-for-each-column-of-a-numpy-ndarray), [SOURCE08](https://www.codecademy.com/learn/intro-statistics-numpy)


In [55]:
arr5 = np.array([4,8,6,2,5,7,9,1])
arr5

array([4, 8, 6, 2, 5, 7, 9, 1])

In [56]:
np.mean(arr5)

5.25

In [57]:
np.median(arr5)


5.5

In [58]:
np.std(arr5)

2.6339134382131846

In [59]:
np.var(arr5)

6.9375

In [60]:
np.average(arr5)

5.25

In [61]:
np.sort(arr5)

array([1, 2, 4, 5, 6, 7, 8, 9])

In [63]:
np.percentile(arr5, 1)

1.07

In [64]:
np.percentile(arr5, 2)

1.1400000000000001